<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
        {
            $countries = [
                ['id' => 1, 'country_code' => 'AF', 'country_name' => 'Afghanistan', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 2, 'country_code' => 'AL', 'country_name' => 'Albania', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 3, 'country_code' => 'DZ', 'country_name' => 'Algeria', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 4, 'country_code' => 'DS', 'country_name' => 'American Samoa', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 5, 'country_code' => 'AD', 'country_name' => 'Andorra', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 6, 'country_code' => 'AO', 'country_name' => 'Angola', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 7, 'country_code' => 'AI', 'country_name' => 'Anguilla', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 8, 'country_code' => 'AQ', 'country_name' => 'Antarctica', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 9, 'country_code' => 'AG', 'country_name' => 'Antigua and Barbuda', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 10, 'country_code' => 'AR', 'country_name' => 'Argentina', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 11, 'country_code' => 'AM', 'country_name' => 'Armenia', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 12, 'country_code' => 'AW', 'country_name' => 'Aruba', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 13, 'country_code' => 'AU', 'country_name' => 'Australia', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 14, 'country_code' => 'AT', 'country_name' => 'Austria', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 15, 'country_code' => 'AZ', 'country_name' => 'Azerbaijan', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 16, 'country_code' => 'BS', 'country_name' => 'Bahamas', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 17, 'country_code' => 'BH', 'country_name' => 'Bahrain', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 18, 'country_code' => 'BD', 'country_name' => 'Bangladesh', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 19, 'country_code' => 'BB', 'country_name' => 'Barbados', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 20, 'country_code' => 'BY', 'country_name' => 'Belarus', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 21, 'country_code' => 'BE', 'country_name' => 'Belgium', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 22, 'country_code' => 'BZ', 'country_name' => 'Belize', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 23, 'country_code' => 'BJ', 'country_name' => 'Benin', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 24, 'country_code' => 'BM', 'country_name' => 'Bermuda', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 25, 'country_code' => 'BT', 'country_name' => 'Bhutan', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 26, 'country_code' => 'BO', 'country_name' => 'Bolivia', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 27, 'country_code' => 'BA', 'country_name' => 'Bosnia and Herzegovina', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 28, 'country_code' => 'BW', 'country_name' => 'Botswana', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 29, 'country_code' => 'BV', 'country_name' => 'Bouvet Island', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 30, 'country_code' => 'BR', 'country_name' => 'Brazil', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 31, 'country_code' => 'IO', 'country_name' => 'British Indian Ocean Territory', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 32, 'country_code' => 'BN', 'country_name' => 'Brunei Darussalam', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 33, 'country_code' => 'BG', 'country_name' => 'Bulgaria', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 34, 'country_code' => 'BF', 'country_name' => 'Burkina Faso', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 35, 'country_code' => 'BI', 'country_name' => 'Burundi', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 36, 'country_code' => 'KH', 'country_name' => 'Cambodia', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 37, 'country_code' => 'CM', 'country_name' => 'Cameroon', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 38, 'country_code' => 'CA', 'country_name' => 'Canada', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 39, 'country_code' => 'CV', 'country_name' => 'Cape Verde', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 40, 'country_code' => 'KY', 'country_name' => 'Cayman Islands', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 41, 'country_code' => 'CF', 'country_name' => 'Central African Republic', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 42, 'country_code' => 'TD', 'country_name' => 'Chad', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 43, 'country_code' => 'CL', 'country_name' => 'Chile', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 44, 'country_code' => 'CN', 'country_name' => 'China', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 45, 'country_code' => 'CX', 'country_name' => 'Christmas Island', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 46, 'country_code' => 'CC', 'country_name' => 'Cocos (Keeling) Islands', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 47, 'country_code' => 'CO', 'country_name' => 'Colombia', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 48, 'country_code' => 'KM', 'country_name' => 'Comoros', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 49, 'country_code' => 'CD', 'country_name' => 'Congo, Democratic Republic of the', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 50, 'country_code' => 'CG', 'country_name' => 'Congo, Republic of the', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 51, 'country_code' => 'CK', 'country_name' => 'Cook Islands', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 52, 'country_code' => 'CR', 'country_name' => 'Costa Rica', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 53, 'country_code' => 'HR', 'country_name' => 'Croatia', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 54, 'country_code' => 'CU', 'country_name' => 'Cuba', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 55, 'country_code' => 'CW', 'country_name' => 'Curaçao', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 56, 'country_code' => 'CY', 'country_name' => 'Cyprus', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 57, 'country_code' => 'CZ', 'country_name' => 'Czech Republic', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 58, 'country_code' => 'DK', 'country_name' => 'Denmark', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 59, 'country_code' => 'DJ', 'country_name' => 'Djibouti', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 60, 'country_code' => 'DM', 'country_name' => 'Dominica', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 61, 'country_code' => 'DO', 'country_name' => 'Dominican Republic', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 62, 'country_code' => 'EC', 'country_name' => 'Ecuador', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 63, 'country_code' => 'EG', 'country_name' => 'Egypt', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 64, 'country_code' => 'SV', 'country_name' => 'El Salvador', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 65, 'country_code' => 'GQ', 'country_name' => 'Equatorial Guinea', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 66, 'country_code' => 'ER', 'country_name' => 'Eritrea', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 67, 'country_code' => 'EE', 'country_name' => 'Estonia', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 68, 'country_code' => 'SZ', 'country_name' => 'Eswatini', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 69, 'country_code' => 'ET', 'country_name' => 'Ethiopia', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 70, 'country_code' => 'FK', 'country_name' => 'Falkland Islands', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 71, 'country_code' => 'FO', 'country_name' => 'Faroe Islands', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 72, 'country_code' => 'FJ', 'country_name' => 'Fiji', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 73, 'country_code' => 'FI', 'country_name' => 'Finland', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 74, 'country_code' => 'FR', 'country_name' => 'France', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 75, 'country_code' => 'GF', 'country_name' => 'French Guiana', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 76, 'country_code' => 'PF', 'country_name' => 'French Polynesia', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 77, 'country_code' => 'TF', 'country_name' => 'French Southern Territories', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 78, 'country_code' => 'GA', 'country_name' => 'Gabon', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 79, 'country_code' => 'GM', 'country_name' => 'Gambia', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 80, 'country_code' => 'GE', 'country_name' => 'Georgia', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 81, 'country_code' => 'DE', 'country_name' => 'Germany', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 82, 'country_code' => 'GH', 'country_name' => 'Ghana', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 83, 'country_code' => 'GI', 'country_name' => 'Gibraltar', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 84, 'country_code' => 'GR', 'country_name' => 'Greece', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 85, 'country_code' => 'GL', 'country_name' => 'Greenland', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 86, 'country_code' => 'GD', 'country_name' => 'Grenada', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 87, 'country_code' => 'GP', 'country_name' => 'Guadeloupe', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 88, 'country_code' => 'GU', 'country_name' => 'Guam', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 89, 'country_code' => 'GT', 'country_name' => 'Guatemala', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 90, 'country_code' => 'GG', 'country_name' => 'Guernsey', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 91, 'country_code' => 'GN', 'country_name' => 'Guinea', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 92, 'country_code' => 'GW', 'country_name' => 'Guinea-Bissau', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 93, 'country_code' => 'GY', 'country_name' => 'Guyana', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 94, 'country_code' => 'HT', 'country_name' => 'Haiti', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 95, 'country_code' => 'HM', 'country_name' => 'Heard Island and McDonald Islands', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 96, 'country_code' => 'VA', 'country_name' => 'Holy See', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 97, 'country_code' => 'HN', 'country_name' => 'Honduras', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 98, 'country_code' => 'HK', 'country_name' => 'Hong Kong', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 99, 'country_code' => 'HU', 'country_name' => 'Hungary', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 100, 'country_code' => 'IS', 'country_name' => 'Iceland', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 101, 'country_code' => 'IN', 'country_name' => 'India', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 102, 'country_code' => 'ID', 'country_name' => 'Indonesia', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 103, 'country_code' => 'IR', 'country_name' => 'Iran', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 104, 'country_code' => 'IQ', 'country_name' => 'Iraq', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 105, 'country_code' => 'IE', 'country_name' => 'Ireland', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 106, 'country_code' => 'IM', 'country_name' => 'Isle of Man', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 107, 'country_code' => 'IL', 'country_name' => 'Israel', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 108, 'country_code' => 'IT', 'country_name' => 'Italy', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 109, 'country_code' => 'JM', 'country_name' => 'Jamaica', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 110, 'country_code' => 'JP', 'country_name' => 'Japan', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 111, 'country_code' => 'JE', 'country_name' => 'Jersey', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 112, 'country_code' => 'JO', 'country_name' => 'Jordan', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 113, 'country_code' => 'KZ', 'country_name' => 'Kazakhstan', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 114, 'country_code' => 'KE', 'country_name' => 'Kenya', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 115, 'country_code' => 'KI', 'country_name' => 'Kiribati', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 116, 'country_code' => 'KP', 'country_name' => 'Korea, Democratic People\'s Republic of', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 117, 'country_code' => 'KR', 'country_name' => 'Korea, Republic of', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 118, 'country_code' => 'KW', 'country_name' => 'Kuwait', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 119, 'country_code' => 'KG', 'country_name' => 'Kyrgyzstan', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 120, 'country_code' => 'LA', 'country_name' => 'Lao People\'s Democratic Republic', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 121, 'country_code' => 'LV', 'country_name' => 'Latvia', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 122, 'country_code' => 'LB', 'country_name' => 'Lebanon', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 123, 'country_code' => 'LS', 'country_name' => 'Lesotho', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 124, 'country_code' => 'LR', 'country_name' => 'Liberia', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 125, 'country_code' => 'LY', 'country_name' => 'Libya', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 126, 'country_code' => 'LI', 'country_name' => 'Liechtenstein', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 127, 'country_code' => 'LT', 'country_name' => 'Lithuania', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 128, 'country_code' => 'LU', 'country_name' => 'Luxembourg', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 129, 'country_code' => 'MO', 'country_name' => 'Macao', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 130, 'country_code' => 'MG', 'country_name' => 'Madagascar', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 131, 'country_code' => 'MW', 'country_name' => 'Malawi', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 132, 'country_code' => 'MY', 'country_name' => 'Malaysia', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 133, 'country_code' => 'MV', 'country_name' => 'Maldives', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 134, 'country_code' => 'ML', 'country_name' => 'Mali', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 135, 'country_code' => 'MT', 'country_name' => 'Malta', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 136, 'country_code' => 'MH', 'country_name' => 'Marshall Islands', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 137, 'country_code' => 'MQ', 'country_name' => 'Martinique', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 138, 'country_code' => 'MR', 'country_name' => 'Mauritania', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 139, 'country_code' => 'MU', 'country_name' => 'Mauritius', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 140, 'country_code' => 'YT', 'country_name' => 'Mayotte', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 141, 'country_code' => 'MX', 'country_name' => 'Mexico', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 142, 'country_code' => 'FM', 'country_name' => 'Micronesia (Federated States of)', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 143, 'country_code' => 'MD', 'country_name' => 'Moldova', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 144, 'country_code' => 'MC', 'country_name' => 'Monaco', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 145, 'country_code' => 'MN', 'country_name' => 'Mongolia', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 146, 'country_code' => 'ME', 'country_name' => 'Montenegro', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 147, 'country_code' => 'MS', 'country_name' => 'Montserrat', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 148, 'country_code' => 'MA', 'country_name' => 'Morocco', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 149, 'country_code' => 'MZ', 'country_name' => 'Mozambique', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 150, 'country_code' => 'MM', 'country_name' => 'Myanmar', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 151, 'country_code' => 'NA', 'country_name' => 'Namibia', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 152, 'country_code' => 'NR', 'country_name' => 'Nauru', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 153, 'country_code' => 'NP', 'country_name' => 'Nepal', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 154, 'country_code' => 'NL', 'country_name' => 'Netherlands', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 155, 'country_code' => 'NC', 'country_name' => 'New Caledonia', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 156, 'country_code' => 'NZ', 'country_name' => 'New Zealand', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 157, 'country_code' => 'NI', 'country_name' => 'Nicaragua', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 158, 'country_code' => 'NE', 'country_name' => 'Niger', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 159, 'country_code' => 'NG', 'country_name' => 'Nigeria', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 160, 'country_code' => 'NU', 'country_name' => 'Niue', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 161, 'country_code' => 'NF', 'country_name' => 'Norfolk Island', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 162, 'country_code' => 'MP', 'country_name' => 'Northern Mariana Islands', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 163, 'country_code' => 'NO', 'country_name' => 'Norway', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 164, 'country_code' => 'OM', 'country_name' => 'Oman', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 165, 'country_code' => 'PK', 'country_name' => 'Pakistan', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 166, 'country_code' => 'PW', 'country_name' => 'Palau', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 167, 'country_code' => 'PS', 'country_name' => 'Palestine, State of', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 168, 'country_code' => 'PA', 'country_name' => 'Panama', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 169, 'country_code' => 'PG', 'country_name' => 'Papua New Guinea', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 170, 'country_code' => 'PY', 'country_name' => 'Paraguay', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 171, 'country_code' => 'PE', 'country_name' => 'Peru', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 172, 'country_code' => 'PH', 'country_name' => 'Philippines', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 173, 'country_code' => 'PN', 'country_name' => 'Pitcairn', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 174, 'country_code' => 'PL', 'country_name' => 'Poland', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 175, 'country_code' => 'PT', 'country_name' => 'Portugal', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 176, 'country_code' => 'PR', 'country_name' => 'Puerto Rico', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 177, 'country_code' => 'QA', 'country_name' => 'Qatar', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 178, 'country_code' => 'RE', 'country_name' => 'Reunion', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 179, 'country_code' => 'RO', 'country_name' => 'Romania', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 180, 'country_code' => 'RU', 'country_name' => 'Russian Federation', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 181, 'country_code' => 'RW', 'country_name' => 'Rwanda', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 182, 'country_code' => 'BL', 'country_name' => 'Saint Barthélemy', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 183, 'country_code' => 'SH', 'country_name' => 'Saint Helena, Ascension and Tristan da Cunha', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 184, 'country_code' => 'KN', 'country_name' => 'Saint Kitts and Nevis', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 185, 'country_code' => 'LC', 'country_name' => 'Saint Lucia', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 186, 'country_code' => 'MF', 'country_name' => 'Saint Martin (French part)', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 187, 'country_code' => 'PM', 'country_name' => 'Saint Pierre and Miquelon', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 188, 'country_code' => 'VC', 'country_name' => 'Saint Vincent and the Grenadines', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 189, 'country_code' => 'WS', 'country_name' => 'Samoa', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 190, 'country_code' => 'SM', 'country_name' => 'San Marino', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 191, 'country_code' => 'ST', 'country_name' => 'Sao Tome and Principe', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 192, 'country_code' => 'SA', 'country_name' => 'Saudi Arabia', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 193, 'country_code' => 'SN', 'country_name' => 'Senegal', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 194, 'country_code' => 'RS', 'country_name' => 'Serbia', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 195, 'country_code' => 'SC', 'country_name' => 'Seychelles', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 196, 'country_code' => 'SL', 'country_name' => 'Sierra Leone', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 197, 'country_code' => 'SG', 'country_name' => 'Singapore', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 198, 'country_code' => 'SX', 'country_name' => 'Sint Maarten (Dutch part)', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 199, 'country_code' => 'SK', 'country_name' => 'Slovakia', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 200, 'country_code' => 'SI', 'country_name' => 'Slovenia', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 201, 'country_code' => 'SB', 'country_name' => 'Solomon Islands', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 202, 'country_code' => 'SO', 'country_name' => 'Somalia', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 203, 'country_code' => 'ZA', 'country_name' => 'South Africa', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 204, 'country_code' => 'GS', 'country_name' => 'South Georgia and the South Sandwich Islands', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 205, 'country_code' => 'KR', 'country_name' => 'South Korea', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 206, 'country_code' => 'SS', 'country_name' => 'South Sudan', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 207, 'country_code' => 'ES', 'country_name' => 'Spain', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 208, 'country_code' => 'LK', 'country_name' => 'Sri Lanka', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 209, 'country_code' => 'SD', 'country_name' => 'Sudan', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 210, 'country_code' => 'SR', 'country_name' => 'Suriname', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 211, 'country_code' => 'SJ', 'country_name' => 'Svalbard and Jan Mayen', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 212, 'country_code' => 'SZ', 'country_name' => 'Swaziland', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 213, 'country_code' => 'SE', 'country_name' => 'Sweden', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 214, 'country_code' => 'CH', 'country_name' => 'Switzerland', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 215, 'country_code' => 'SY', 'country_name' => 'Syrian Arab Republic', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 216, 'country_code' => 'TW', 'country_name' => 'Taiwan, Province of China', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 217, 'country_code' => 'TJ', 'country_name' => 'Tajikistan', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 218, 'country_code' => 'TZ', 'country_name' => 'Tanzania, United Republic of', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 219, 'country_code' => 'TH', 'country_name' => 'Thailand', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 220, 'country_code' => 'TG', 'country_name' => 'Togo', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 221, 'country_code' => 'TK', 'country_name' => 'Tokelau', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 222, 'country_code' => 'TO', 'country_name' => 'Tonga', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 223, 'country_code' => 'TT', 'country_name' => 'Trinidad and Tobago', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 224, 'country_code' => 'TN', 'country_name' => 'Tunisia', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 225, 'country_code' => 'TR', 'country_name' => 'Turkey', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 226, 'country_code' => 'TM', 'country_name' => 'Turkmenistan', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 227, 'country_code' => 'TC', 'country_name' => 'Turks and Caicos Islands', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 228, 'country_code' => 'TV', 'country_name' => 'Tuvalu', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 229, 'country_code' => 'UG', 'country_name' => 'Uganda', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 230, 'country_code' => 'UA', 'country_name' => 'Ukraine', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 231, 'country_code' => 'AE', 'country_name' => 'United Arab Emirates', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 232, 'country_code' => 'GB', 'country_name' => 'United Kingdom', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 233, 'country_code' => 'US', 'country_name' => 'United States', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 234, 'country_code' => 'UY', 'country_name' => 'Uruguay', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 235, 'country_code' => 'UZ', 'country_name' => 'Uzbekistan', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 236, 'country_code' => 'VU', 'country_name' => 'Vanuatu', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 237, 'country_code' => 'VE', 'country_name' => 'Venezuela, Bolivarian Republic of', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 238, 'country_code' => 'VN', 'country_name' => 'Viet Nam', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 239, 'country_code' => 'WF', 'country_name' => 'Wallis and Futuna', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 240, 'country_code' => 'EH', 'country_name' => 'Western Sahara', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 241, 'country_code' => 'YE', 'country_name' => 'Yemen', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 242, 'country_code' => 'ZM', 'country_name' => 'Zambia', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
                ['id' => 243, 'country_code' => 'ZW', 'country_name' => 'Zimbabwe', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ];
          // Note: Check DatabaseSeeder.php
          \App\Models\Country ::insert($countries);
        }
}
